twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # for options, see: https://vuetifyjs.com/en/components/text-fields#usage
        input_style: 'regular'
    form_themes:
        - 'form/vuetified-form.vue.twig'